name: Main
on: push
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Configure Terraform
        shell: bash
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: us-east-1
          DOMAIN_NAME: example.com
        run: |
          echo "access_key  = \"$AWS_ACCESS_KEY\"" >  test/aws/terraform.tfvars
          echo "secret_key  = \"$AWS_SECRET_KEY\"" >> test/aws/terraform.tfvars
          echo "region      = \"$AWS_REGION\""     >> test/aws/terraform.tfvars
          echo 'name        = "ci"'                >> test/aws/terraform.tfvars
          echo 'environment = "test"'              >> test/aws/terraform.tfvars
          echo "domain      = \"$DOMAIN_NAME\""    >> test/aws/terraform.tfvars
      - name: Terraform Validate
        shell: bash
        run: |
          # terraform is available in the GitHub Actions virtual environment
          cd test/aws
          make keys init validate
